-- MySQL Script generated by MySQL Workbench
-- Tue May 19 22:40:00 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema avaliacao
-- -----------------------------------------------------
-- DB projeto de bloco

-- -----------------------------------------------------
-- Schema avaliacao
--
-- DB projeto de bloco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avaliacao` ;
USE `avaliacao` ;

-- -----------------------------------------------------
-- Table `avaliacao`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`usuario` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `sobrenome` VARCHAR(255) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL,
  `usuario_inc` INT NOT NULL,
  `usuario_alt` INT NULL,
  `nr_versao` INT NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cpf_UNIQUE` ON `avaliacao`.`usuario` (`cpf` ASC);


-- -----------------------------------------------------
-- Table `avaliacao`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`perfil` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NULL,
  `administrador` BINARY NULL,
  `professor` BINARY NULL,
  `aluno` BINARY NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL,
  `usuario_inc` INT NOT NULL,
  `usuario_alt` INT NULL,
  `nr_versao` INT NOT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`usuario_perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`usuario_perfil` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`usuario_perfil` (
  `id_usuario_perfil` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_usuario_perfil`),
  CONSTRAINT `iduser`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `avaliacao`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `iduser_idx` ON `avaliacao`.`usuario_perfil` (`id_usuario` ASC);

CREATE INDEX `perfil_idx` ON `avaliacao`.`usuario_perfil` (`id_perfil` ASC);


-- -----------------------------------------------------
-- Table `avaliacao`.`modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`modulo` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`modulo` (
  `id_modulo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL,
  `usuario_inc` INT NOT NULL,
  `usuario_alt` INT NULL,
  `nr_versao` INT NOT NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`turma` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `id_professor` INT NOT NULL,
  `modulo_id_modulo` INT NOT NULL,
  `numero` INT UNSIGNED NOT NULL,
  `dt_inicial` DATETIME NOT NULL,
  `dt_final` DATETIME NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL,
  `usuario_inc` INT NOT NULL,
  `usuario_alt` INT NULL,
  `nr_versao` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  CONSTRAINT `fk_turma_modulo`
    FOREIGN KEY (`modulo_id_modulo`)
    REFERENCES `avaliacao`.`modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_usuario1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_turma_modulo_idx` ON `avaliacao`.`turma` (`modulo_id_modulo` ASC);

CREATE INDEX `fk_turma_usuario1_idx` ON `avaliacao`.`turma` (`id_professor` ASC);


-- -----------------------------------------------------
-- Table `avaliacao`.`aluno_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`aluno_turma` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`aluno_turma` (
  `id_aluno_turma` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_turma` INT NOT NULL,
  PRIMARY KEY (`id_aluno_turma`),
  CONSTRAINT `iduser`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idturma`
    FOREIGN KEY (`id_turma`)
    REFERENCES `avaliacao`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idturma_idx` ON `avaliacao`.`aluno_turma` (`id_turma` ASC);

CREATE INDEX `idaluno_idx` ON `avaliacao`.`aluno_turma` (`id_aluno_turma` ASC);


-- -----------------------------------------------------
-- Table `avaliacao`.`formulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`formulario` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`formulario` (
  `id_formulario` INT NOT NULL,
  `descricao` TEXT NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL,
  `usuario_inc` INT NOT NULL,
  `usuario_alt` INT NULL,
  `nr_versao` INT NOT NULL,
  PRIMARY KEY (`id_formulario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`topico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`topico` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`topico` (
  `id_topico` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_topico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`pergunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`pergunta` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`pergunta` (
  `id_pergunta` INT NOT NULL,
  `id_formulario` INT NOT NULL,
  `id_topico` INT NOT NULL,
  `pergunta` VARCHAR(255) NOT NULL,
  `peso` DECIMAL(5,2) NULL,
  `objetiva` BINARY NOT NULL,
  `justificativa` BINARY NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL,
  `usuario_inc` INT NOT NULL,
  `usuario_alt` INT NULL,
  `nr_versao` INT NOT NULL,
  PRIMARY KEY (`id_pergunta`),
  CONSTRAINT `idformulario`
    FOREIGN KEY (`id_formulario`)
    REFERENCES `avaliacao`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtopico`
    FOREIGN KEY (`id_topico`)
    REFERENCES `avaliacao`.`topico` (`id_topico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idformulario_idx` ON `avaliacao`.`pergunta` (`id_formulario` ASC);

CREATE INDEX `idtopico_idx` ON `avaliacao`.`pergunta` (`id_topico` ASC);


-- -----------------------------------------------------
-- Table `avaliacao`.`resposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`resposta` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`resposta` (
  `id_resposta` INT NOT NULL,
  `id_pergunta` INT NOT NULL,
  `nota` VARCHAR(45) NOT NULL,
  `resposta` DECIMAL(5,2) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL,
  `usuario_inc` INT NOT NULL,
  `usuario_alt` INT NULL,
  `nr_versao` INT NOT NULL,
  PRIMARY KEY (`id_resposta`),
  CONSTRAINT `idpergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `avaliacao`.`pergunta` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idpergunta_idx` ON `avaliacao`.`resposta` (`id_pergunta` ASC);


-- -----------------------------------------------------
-- Table `avaliacao`.`turma_formulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`turma_formulario` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`turma_formulario` (
  `id_turma_formulario` INT NOT NULL AUTO_INCREMENT,
  `id_turma` INT NOT NULL,
  `id_formulario` INT NOT NULL,
  `dt_inicio_avaliacao` DATETIME NOT NULL,
  `dt_final_avaliacao` DATETIME NOT NULL,
  `texto_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_turma_formulario`),
  CONSTRAINT `idformulario`
    FOREIGN KEY (`id_formulario`)
    REFERENCES `avaliacao`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idturma`
    FOREIGN KEY (`id_turma`)
    REFERENCES `avaliacao`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idformulario_idx` ON `avaliacao`.`turma_formulario` (`id_formulario` ASC);

CREATE INDEX `idturma_idx` ON `avaliacao`.`turma_formulario` (`id_turma` ASC);


-- -----------------------------------------------------
-- Table `avaliacao`.`aluno_avaliacao_modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`aluno_avaliacao_modulo` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`aluno_avaliacao_modulo` (
  `id_aluno_avalia_modulo` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_turma_formulario` INT NOT NULL,
  `dt_avaliacao` DATE NOT NULL,
  `concluida` BINARY NOT NULL,
  `transmitida` BINARY NOT NULL,
  `usuario_turma_usuario_id_user` INT NULL,
  `usuario_turma_turma_id_turma` INT NULL,
  PRIMARY KEY (`id_aluno_avalia_modulo`, `usuario_turma_usuario_id_user`, `usuario_turma_turma_id_turma`),
  CONSTRAINT `iduser`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `avaliacao`.`aluno_turma` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_turma_formulario`
    FOREIGN KEY (`id_turma_formulario`)
    REFERENCES `avaliacao`.`turma_formulario` (`id_turma_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `iduser_idx` ON `avaliacao`.`aluno_avaliacao_modulo` (`id_usuario` ASC);

CREATE INDEX `id_turma_formulario_idx` ON `avaliacao`.`aluno_avaliacao_modulo` (`id_turma_formulario` ASC);


-- -----------------------------------------------------
-- Table `avaliacao`.`avaliacao_resposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`avaliacao_resposta` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`avaliacao_resposta` (
  `id_avaliacao_resposta` INT NOT NULL,
  `id_aluno_avalia_modulo` INT NOT NULL,
  `id_pergunta` INT NOT NULL,
  `id_resposta` INT NULL,
  `texto` VARCHAR(255) NULL,
  PRIMARY KEY (`id_avaliacao_resposta`),
  CONSTRAINT `idalunoAvaliaModulo`
    FOREIGN KEY (`id_aluno_avalia_modulo`)
    REFERENCES `avaliacao`.`aluno_avaliacao_modulo` (`id_aluno_avalia_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idpergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `avaliacao`.`pergunta` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idresposta`
    FOREIGN KEY (`id_resposta`)
    REFERENCES `avaliacao`.`resposta` (`id_resposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idalunoAvaliaModulo_idx` ON `avaliacao`.`avaliacao_resposta` (`id_aluno_avalia_modulo` ASC);

CREATE INDEX `idpergunta_idx` ON `avaliacao`.`avaliacao_resposta` (`id_pergunta` ASC);

CREATE INDEX `idresposta_idx` ON `avaliacao`.`avaliacao_resposta` (`id_resposta` ASC);


-- -----------------------------------------------------
-- Table `avaliacao`.`teste`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`teste` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`teste` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`usuario_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`usuario_turma` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`usuario_turma` (
  `id_usuario_turma` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_user` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_usuario_turma`),
  CONSTRAINT `fk_usuario_has_turma_usuario1`
    FOREIGN KEY (`usuario_id_user`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_has_turma_turma1_idx` ON `avaliacao`.`usuario_turma` (`turma_id_turma` ASC);

CREATE INDEX `fk_usuario_has_turma_usuario1_idx` ON `avaliacao`.`usuario_turma` (`usuario_id_user` ASC);


-- -----------------------------------------------------
-- Table `avaliacao`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`curso` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`curso` (
  `id_cusro` INT NOT NULL,
  `nomeCurso` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cusro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`curso_modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`curso_modulo` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`curso_modulo` (
  `id_curso_modulo` INT NOT NULL,
  `id_modulo` INT NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_curso_modulo`),
  CONSTRAINT `id_modulo`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `avaliacao`.`modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `avaliacao`.`curso` (`id_cusro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_modulo_idx` ON `avaliacao`.`curso_modulo` (`id_modulo` ASC);

CREATE INDEX `id_curso_idx` ON `avaliacao`.`curso_modulo` (`id_curso` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
