
-- MySQL Script generated by MySQL Workbench
-- 07/28/15 16:15:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema avaliacao
-- -----------------------------------------------------
-- DB projeto de bloco
DROP SCHEMA IF EXISTS `avaliacao` ;

-- -----------------------------------------------------
-- Schema avaliacao
--
-- DB projeto de bloco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avaliacao` ;
-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
USE `avaliacao` ;

-- -----------------------------------------------------
-- Table `avaliacao`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`usuario` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(255) NOT NULL COMMENT '',
  `sobrenome` VARCHAR(255) NOT NULL COMMENT '',
  `dt_nascimento` DATE NOT NULL COMMENT '',
  `cpf` VARCHAR(11) NOT NULL COMMENT '',
  `email` VARCHAR(100) NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '')
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cpf_UNIQUE` ON `avaliacao`.`usuario` (`cpf` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `avaliacao`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`perfil` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(200) NULL COMMENT '',
  `administrador` BINARY NULL COMMENT '',
  `professor` BINARY NULL COMMENT '',
  `aluno` BINARY NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_perfil`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`usuario_perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`usuario_perfil` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`usuario_perfil` (
  `id_usuario_perfil` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  `id_perfil` INT NOT NULL COMMENT '',  
  PRIMARY KEY (`id_usuario_perfil`)  COMMENT '',
  CONSTRAINT `iduser`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `avaliacao`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `iduser_idx` ON `avaliacao`.`usuario_perfil` (`id_usuario` ASC)  COMMENT '';

CREATE INDEX `perfil_idx` ON `avaliacao`.`usuario_perfil` (`id_perfil` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `avaliacao`.`modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`modulo` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`modulo` (
  `id_modulo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(255) NOT NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_modulo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`formulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`formulario` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`formulario` (
  `id_formulario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` TEXT NOT NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_formulario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`turma` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_professor` INT NOT NULL COMMENT '',
  `modulo_id_modulo` INT NOT NULL COMMENT '',
  `numero` INT UNSIGNED NOT NULL COMMENT '',
  `dt_inicial` DATETIME NOT NULL COMMENT '',
  `dt_final` DATETIME NOT NULL COMMENT '',
  `dt_inicio_avaliacao` DATETIME NOT NULL COMMENT '',
  `dt_final_avaliacao` DATETIME NOT NULL COMMENT '',
  `texto_email` VARCHAR(255) NOT NULL COMMENT '',
  `id_formulario` INT NOT NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',  
  PRIMARY KEY (`id_turma`)  COMMENT '',
  CONSTRAINT `fk_turma_modulo`
    FOREIGN KEY (`modulo_id_modulo`)
    REFERENCES `avaliacao`.`modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_usuario1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario`
    FOREIGN KEY (`id_formulario`)
    REFERENCES `avaliacao`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_turma_modulo_idx` ON `avaliacao`.`turma` (`modulo_id_modulo` ASC)  COMMENT '';

CREATE INDEX `fk_turma_usuario1_idx` ON `avaliacao`.`turma` (`id_professor` ASC)  COMMENT '';

CREATE INDEX `fk_formulario_idx` ON `avaliacao`.`turma` (`id_formulario` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `avaliacao`.`aluno_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`aluno_turma` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`aluno_turma` (
  `id_aluno_turma` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  `id_turma` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_aluno_turma`)  COMMENT '',
  CONSTRAINT `iduser_idx`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idturma_idx`
    FOREIGN KEY (`id_turma`)
    REFERENCES `avaliacao`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_turma_idx` ON `avaliacao`.`aluno_turma` (`id_turma` ASC)  COMMENT '';

CREATE INDEX `id_usuario_idx` ON `avaliacao`.`aluno_turma` (`id_usuario` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `avaliacao`.`topico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`topico` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`topico` (
  `id_topico` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NOT NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_topico`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`pergunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`pergunta` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`pergunta` (
  `id_pergunta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_formulario` INT NOT NULL COMMENT '',
  `id_topico` INT NOT NULL COMMENT '',
  `pergunta` VARCHAR(255) NOT NULL COMMENT '',
  `peso` DECIMAL(5,2) NULL COMMENT '',
  `objetiva` BINARY NOT NULL COMMENT '',
  `justificativa` BINARY NOT NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_pergunta`)  COMMENT '',
  CONSTRAINT `idformulario`
    FOREIGN KEY (`id_formulario`)
    REFERENCES `avaliacao`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtopico`
    FOREIGN KEY (`id_topico`)
    REFERENCES `avaliacao`.`topico` (`id_topico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idformulario_idx` ON `avaliacao`.`pergunta` (`id_formulario` ASC)  COMMENT '';

CREATE INDEX `idtopico_idx` ON `avaliacao`.`pergunta` (`id_topico` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `avaliacao`.`resposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`resposta` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`resposta` (
  `id_resposta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_pergunta` INT NOT NULL COMMENT '',
  `nota` VARCHAR(45) NOT NULL COMMENT '',
  `resposta` DECIMAL(5,2) NOT NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_resposta`)  COMMENT '',
  CONSTRAINT `idpergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `avaliacao`.`pergunta` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idpergunta_idx` ON `avaliacao`.`resposta` (`id_pergunta` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `avaliacao`.`aluno_avaliacao_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`aluno_avaliacao_turma` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`aluno_avaliacao_turma` (
  `id_aluno_avalia_turma` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_aluno` INT NOT NULL COMMENT '',
  `id_turma` INT NOT NULL COMMENT '',
  `dt_avaliacao` DATE NOT NULL COMMENT '',
  `concluida` BINARY NOT NULL COMMENT '',
  `transmitida` BINARY NOT NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_aluno_avalia_turma`)  COMMENT '',
  CONSTRAINT `id_aluno_idx`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_turma_idx`
    FOREIGN KEY (`id_turma`)
    REFERENCES `avaliacao`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_aluno_idx` ON `avaliacao`.`usuario` (`id_usuario` ASC)  COMMENT '';
CREATE INDEX `id_turma_idx` ON `avaliacao`.`turma` (`id_turma` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `avaliacao`.`avaliacao_resposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`avaliacao_resposta` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`avaliacao_resposta` (
  `id_avaliacao_resposta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_aluno_avalia_modulo` INT NOT NULL COMMENT '',
  `id_pergunta` INT NOT NULL COMMENT '',
  `id_resposta` INT NULL COMMENT '',
  `texto` VARCHAR(255) NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_avaliacao_resposta`)  COMMENT '',
  CONSTRAINT `ARidalunoAvaliaModulo`
    FOREIGN KEY (`id_aluno_avalia_modulo`)
    REFERENCES `avaliacao`.`aluno_avaliacao_turma` (`id_aluno_avalia_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ARidpergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `avaliacao`.`pergunta` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ARidresposta`
    FOREIGN KEY (`id_resposta`)
    REFERENCES `avaliacao`.`resposta` (`id_resposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idalunoAvaliaModulo_idx` ON `avaliacao`.`avaliacao_resposta` (`id_aluno_avalia_modulo` ASC)  COMMENT '';

CREATE INDEX `idpergunta_idx` ON `avaliacao`.`avaliacao_resposta` (`id_pergunta` ASC)  COMMENT '';

CREATE INDEX `idresposta_idx` ON `avaliacao`.`avaliacao_resposta` (`id_resposta` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `avaliacao`.`usuario_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`usuario_turma` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`usuario_turma` (
  `id_usuario_turma` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `usuario_id_user` INT NOT NULL COMMENT '',
  `turma_id_turma` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario_turma`)  COMMENT '',
  CONSTRAINT `fk_usuario_has_turma_usuario1`
    FOREIGN KEY (`usuario_id_user`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_has_turma_turma1_idx` ON `avaliacao`.`usuario_turma` (`turma_id_turma` ASC)  COMMENT '';

CREATE INDEX `fk_usuario_has_turma_usuario1_idx` ON `avaliacao`.`usuario_turma` (`usuario_id_user` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `avaliacao`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`curso` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nomeCurso` VARCHAR(255) NOT NULL COMMENT '',
  `dt_inclusao` DATETIME NOT NULL COMMENT '',
  `dt_alteracao` DATETIME NULL COMMENT '',
  `usuario_inc` INT NOT NULL COMMENT '',
  `usuario_alt` INT NULL COMMENT '',
  `nr_versao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_curso`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacao`.`curso_modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacao`.`curso_modulo` ;

CREATE TABLE IF NOT EXISTS `avaliacao`.`curso_modulo` (
  `id_curso_modulo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_modulo` INT NOT NULL COMMENT '',
  `id_curso` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_curso_modulo`)  COMMENT '',
  CONSTRAINT `id_modulo`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `avaliacao`.`modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `avaliacao`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_modulo_idx` ON `avaliacao`.`curso_modulo` (`id_modulo` ASC)  COMMENT '';

CREATE INDEX `id_curso_idx` ON `avaliacao`.`curso_modulo` (`id_curso` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
