-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 15:26:12 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema avaliacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema avaliacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avaliacao` DEFAULT CHARACTER SET latin1 ;
USE `avaliacao` ;

-- -----------------------------------------------------
-- Table `avaliacao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `sobrenome` VARCHAR(255) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `user` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(150) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC),
  INDEX `id_aluno_idx` (`id_usuario` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`formulario` (
  `id_formulario` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_formulario`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`modulo` (
  `id_modulo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`turma` (
  `id_turma` INT(11) NOT NULL AUTO_INCREMENT,
  `id_professor` INT(11) NOT NULL,
  `modulo_id_modulo` INT(11) NOT NULL,
  `numero` INT(10) UNSIGNED NOT NULL,
  `dt_inicial` DATETIME NOT NULL,
  `dt_final` DATETIME NOT NULL,
  `dt_inicio_avaliacao` DATETIME NOT NULL,
  `dt_final_avaliacao` DATETIME NOT NULL,
  `texto_email` VARCHAR(255) NOT NULL,
  `id_formulario` INT(11) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_turma_modulo_idx` (`modulo_id_modulo` ASC),
  INDEX `fk_turma_usuario1_idx` (`id_professor` ASC),
  INDEX `fk_formulario_idx` (`id_formulario` ASC),
  INDEX `id_turma_idx` (`id_turma` ASC),
  CONSTRAINT `fk_formulario`
    FOREIGN KEY (`id_formulario`)
    REFERENCES `avaliacao`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_modulo`
    FOREIGN KEY (`modulo_id_modulo`)
    REFERENCES `avaliacao`.`modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_usuario1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`aluno_avaliacao_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`aluno_avaliacao_turma` (
  `id_aluno_avalia_turma` INT(11) NOT NULL AUTO_INCREMENT,
  `id_aluno` INT(11) NOT NULL,
  `id_turma` INT(11) NOT NULL,
  `dt_avaliacao` DATE NOT NULL,
  `concluida` BIT(1) NOT NULL,
  `transmitida` BIT(1) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_aluno_avalia_turma`),
  INDEX `id_aluno_idx` (`id_aluno` ASC),
  INDEX `id_turma_idx` (`id_turma` ASC),
  CONSTRAINT `id_aluno_idx`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_turma_idx`
    FOREIGN KEY (`id_turma`)
    REFERENCES `avaliacao`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`aluno_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`aluno_turma` (
  `id_aluno_turma` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_turma` INT(11) NOT NULL,
  PRIMARY KEY (`id_aluno_turma`),
  INDEX `id_turma_idx` (`id_turma` ASC),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `idturma_idx`
    FOREIGN KEY (`id_turma`)
    REFERENCES `avaliacao`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iduser_idx`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`topico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`topico` (
  `id_topico` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_topico`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`pergunta` (
  `id_pergunta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_formulario` INT(11) NOT NULL,
  `id_topico` INT(11) NOT NULL,
  `pergunta` VARCHAR(255) NOT NULL,
  `peso` DECIMAL(5,2) NULL DEFAULT NULL,
  `objetiva` BIT(1) NOT NULL,
  `justificativa` BIT(1) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_pergunta`),
  INDEX `idformulario_idx` (`id_formulario` ASC),
  INDEX `idtopico_idx` (`id_topico` ASC),
  CONSTRAINT `idformulario`
    FOREIGN KEY (`id_formulario`)
    REFERENCES `avaliacao`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtopico`
    FOREIGN KEY (`id_topico`)
    REFERENCES `avaliacao`.`topico` (`id_topico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`resposta` (
  `id_resposta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pergunta` INT(11) NOT NULL,
  `nota` VARCHAR(45) NOT NULL,
  `resposta` DECIMAL(5,2) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_resposta`),
  INDEX `idpergunta_idx` (`id_pergunta` ASC),
  CONSTRAINT `idpergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `avaliacao`.`pergunta` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`avaliacao_resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`avaliacao_resposta` (
  `id_avaliacao_resposta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_aluno_avalia_modulo` INT(11) NOT NULL,
  `id_pergunta` INT(11) NOT NULL,
  `id_resposta` INT(11) NULL DEFAULT NULL,
  `texto` VARCHAR(255) NULL DEFAULT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_avaliacao_resposta`),
  INDEX `idalunoAvaliaModulo_idx` (`id_aluno_avalia_modulo` ASC),
  INDEX `idpergunta_idx` (`id_pergunta` ASC),
  INDEX `idresposta_idx` (`id_resposta` ASC),
  CONSTRAINT `ARidalunoAvaliaModulo`
    FOREIGN KEY (`id_aluno_avalia_modulo`)
    REFERENCES `avaliacao`.`aluno_avaliacao_turma` (`id_aluno_avalia_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ARidpergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `avaliacao`.`pergunta` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ARidresposta`
    FOREIGN KEY (`id_resposta`)
    REFERENCES `avaliacao`.`resposta` (`id_resposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`curso` (
  `id_curso` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeCurso` VARCHAR(255) NOT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`curso_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`curso_modulo` (
  `id_curso_modulo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_modulo` INT(11) NOT NULL,
  `id_curso` INT(11) NOT NULL,
  PRIMARY KEY (`id_curso_modulo`),
  INDEX `id_modulo_idx` (`id_modulo` ASC),
  INDEX `id_curso_idx` (`id_curso` ASC),
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `avaliacao`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_modulo`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `avaliacao`.`modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`grupo` (
  `grupo` VARCHAR(40) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`grupo`, `usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`perfil` (
  `id_perfil` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NULL DEFAULT NULL,
  `administrador` BIT(1) NULL DEFAULT NULL,
  `professor` BIT(1) NULL DEFAULT NULL,
  `aluno` BIT(1) NULL DEFAULT NULL,
  `dt_inclusao` DATETIME NOT NULL,
  `dt_alteracao` DATETIME NULL DEFAULT NULL,
  `usuario_inc` INT(11) NOT NULL,
  `usuario_alt` INT(11) NULL DEFAULT NULL,
  `nr_versao` INT(11) NOT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`usuario_perfil` (
  `id_usuario_perfil` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_perfil` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario_perfil`),
  INDEX `iduser_idx` (`id_usuario` ASC),
  INDEX `perfil_idx` (`id_perfil` ASC),
  CONSTRAINT `iduser`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `avaliacao`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `avaliacao`.`usuario_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`usuario_turma` (
  `id_usuario_turma` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id_user` INT(11) NOT NULL,
  `turma_id_turma` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario_turma`),
  INDEX `fk_usuario_has_turma_turma1_idx` (`turma_id_turma` ASC),
  INDEX `fk_usuario_has_turma_usuario1_idx` (`usuario_id_user` ASC),
  CONSTRAINT `FK_gipnyjva78a74r1uc283wll8b`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `avaliacao`.`turma` (`id_turma`),
  CONSTRAINT `fk_usuario_has_turma_usuario1`
    FOREIGN KEY (`usuario_id_user`)
    REFERENCES `avaliacao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
